# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac8453c281f6d4ee5a72d176fa78a2988a7b2dc1b309aa35449e8ba4390996c6457e4b8ce0296f17b8b5dac788141b6823020b79a91f8c656f7420af00aaf110

test:
  secret_key_base: 0ab60a862ad7dbc69b3b03c28fd6c73bb3c649391bbfe0e43e7f029523d981ac6ee1e1ad0bc7b52ead36b638deca0ec9b5203dd36db74adf6e84875252b4fc37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
